/*
 * Hello RESTful API Sutel
 *
 * Hello Welcome to 'Sutelllll'
 *
 * API version: 1
 * Contact: sulistyhm.03@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse200 struct {
	Success bool `json:"success,omitempty"`
}
