/*
 * Hello RESTful API Sutel
 *
 * Hello Welcome to 'Sutelllll'
 *
 * API version: 1
 * Contact: sulistyhm.03@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Hello struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Priority float64 `json:"priority,omitempty"`
	Tags []string `json:"tags,omitempty"`
}
